ALTER TABLE settings ADD COLUMN IF NOT EXISTS pingram_daily_cap INTEGER NOT NULL DEFAULT 30;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS pingram_min_delay INTEGER NOT NULL DEFAULT 5;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS pingram_max_delay INTEGER NOT NULL DEFAULT 20;
